# Generated by Django 5.0.2 on 2024-02-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='invoices',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.customers'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.TextField(blank=True, choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='unpaid', null=True),
        ),
    ]
