# Generated by Django 5.0.2 on 2024-02-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customerid',
            new_name='uniqueid',
        ),
        migrations.AddField(
            model_name='invoices',
            name='uniqueid',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
