# Generated by Django 5.0.2 on 2024-02-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
