# Generated by Django 5.0.2 on 2024-02-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_remove_invoices_is_active_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='is_active',
        ),
    ]
