# Generated by Django 5.0.2 on 2024-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_remove_invoices_customer_testimonials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
