# Generated by Django 5.0 on 2024-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
