# Generated by Django 5.0 on 2024-05-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
